### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AlekseiNovoselov** [inappstory/android-sdk#3]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.inappstory.sdk.InAppStoryService.getUserId()' on a null object reference
       at com.inappstory.sdk.stories.utils.SessionManager$2.onSuccess(SessionManager.java:168)
       at com.inappstory.sdk.stories.utils.SessionManager$2.onSuccess(SessionManager.java:161)
       at com.inappstory.sdk.network.Request$1.onPostExecute(Request.java:170)
       at com.inappstory.sdk.network.Request$1.onPostExecute(Request.java:137)
       at android.os.AsyncTask.finish(AsyncTask.java:755)
       at android.os.AsyncTask.access$900(AsyncTask.java:192)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```
context:
it happens after calling `InAppStoryManager.destroy()` on logout

**Comment by paperrose** [comment]
Thank you for report!

This bug fixed in version 1.5.17 and version 1.6.1
