### ISSUE TITLE
InAppStoryService.isConnected

### ISSUE THREAD

**Issue by Ivashkin-aa** [inappstory/android-sdk#5]
```
Fatal Exception: d5.a: Application Not Responding
Caused by d5.a$a$a: main (state = RUNNABLE)
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:672)
       at android.net.IConnectivityManager$Stub$Proxy.getActiveNetworkInfo(IConnectivityManager.java:1722)
       at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:1351)
       at com.inappstory.sdk.InAppStoryService.isConnected(InAppStoryService.java:303)
       at com.inappstory.sdk.stories.statistic.OldStatisticManager.sendStatistic(OldStatisticManager.java:130)
       at com.inappstory.sdk.stories.statistic.OldStatisticManager$1.run(OldStatisticManager.java:79)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8380)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

used version 1.12.0

**Comment by paperrose** [comment]
fixed in 1.12.7, 1.13.3, 1.14.2+
